### ISSUE TITLE
Genome download fails and new tool version 4.5 won't work with older DB version 4.3 provided

### ISSUE THREAD

**Issue by moldach** [pcingola/SnpEff#244]
When I run `java -jar snpEff.jar databases | grep -i Homo_sapiens` I see:

```
[moldach@cdr774 snpEff]$ java -jar snpEff.jar databases | grep -i Homo_sapiens
GRCh37.75                                                       Homo_sapiens                                                                                                    http://downloads.sourceforge.net/project/snpeff/databases/v4_5/snpEff_v4_5_GRCh37.75.zip
GRCh38.99                                                       Homo_sapiens                                                                                                    http://downloads.sourceforge.net/project/snpeff/databases/v4_5/snpEff_v4_5_GRCh38.99.zip
hg19                                                            Homo_sapiens (UCSC)                                                                                             http://downloads.sourceforge.net/project/snpeff/databases/v4_5/snpEff_v4_5_hg19.zip
hg19kg                                                          Homo_sapiens (UCSC KnownGenes)                                                                                  http://downloads.sourceforge.net/project/snpeff/databases/v4_5/snpEff_v4_5_hg19kg.zip
hg38                                                            Homo_sapiens (UCSC)                                                                                             http://downloads.sourceforge.net/project/snpeff/databases/v4_5/snpEff_v4_5_hg38.zip
hg38kg                                                          Homo_sapiens (UCSC KnownGenes)                                                                                  http://downloads.sourceforge.net/project/snpeff/databases/v4_5/snpEff_v4_5_hg38kg.zip
testHg19ChrM                                                    Homo_sapiens (UCSC)                                                                                             http://downloads.sourceforge.net/project/snpeff/databases/v4_5/snpEff_v4_5_testHg19ChrM.zip
```

Trying to download produces an error:

```

[moldach@cdr774 snpEff]$ java -Xmx4g -jar snpEff.jar GRCh37.75 examples/test.chr22.vcf > test.chr22.ann.vcf
00:00:00        ERROR while connecting to http://downloads.sourceforge.net/project/snpeff/databases/v4_5/snpEff_v4_5_GRCh37.75.zip
java.lang.RuntimeException: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.
        at org.snpeff.util.Download.download(Download.java:178)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.downloadAndInstall(SnpEffCmdDownload.java:32)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.runDownloadGenome(SnpEffCmdDownload.java:86)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.run(SnpEffCmdDownload.java:72)
        at org.snpeff.SnpEff.run(SnpEff.java:1233)
        at org.snpeff.SnpEff.loadDb(SnpEff.java:520)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:939)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:922)
        at org.snpeff.SnpEff.run(SnpEff.java:1194)
        at org.snpeff.SnpEff.main(SnpEff.java:167)
Caused by: java.lang.RuntimeException: File not found on the server. Make sure the database name is correct.
        at org.snpeff.util.Download.download(Download.java:127)
        ... 9 more
java.lang.RuntimeException: Genome download failed!
        at org.snpeff.SnpEff.loadDb(SnpEff.java:521)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:939)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:922)
        at org.snpeff.SnpEff.run(SnpEff.java:1194)
        at org.snpeff.SnpEff.main(SnpEff.java:167)
```

Navigating to `http://downloads.sourceforge.net/project/snpeff/databases/v4_5/snpEff_v4_5_GRCh37.75.zip` does not work. [There is _no folder for version 4.5_  ](https://sourceforge.net/projects/snpeff/files/databases/) which means I cannot download this manually either.

If I try to download from version 4.3 (`snpEff_v4_3_GRCh37.87.zip`) and extract the downloaded archive in the `data/` subfolder of the SnpEff installation I get the following error that this DB version won't work with the new tool:

```
[moldach@cedar1 data]$ java -Xmx3g -jar ~/bin/snpEff/snpEff.jar databases | grep -i Homo_sapiens
^C
[moldach@cedar1 data]$ java -Xmx3g -jar ~/bin/snpEff/snpEff.jar GRCh37.87 ~/bin/snpEff/examples/test.chr22.vcf > test.chr22.ann.vcf
java.lang.RuntimeException: Database file '/home/moldach/bin/snpEff/./data/GRCh37.87/snpEffectPredictor.bin' is not compatible with this program version:
        Database version : '4.3'
        Program version  : '4.5'
Try installing the appropriate database.
        at org.snpeff.serializer.MarkerSerializer.load(MarkerSerializer.java:160)
        at org.snpeff.snpEffect.SnpEffectPredictor.load(SnpEffectPredictor.java:55)
        at org.snpeff.snpEffect.Config.loadSnpEffectPredictor(Config.java:579)
        at org.snpeff.SnpEff.loadDb(SnpEff.java:525)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:939)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:922)
        at org.snpeff.SnpEff.run(SnpEff.java:1194)
        at org.snpeff.SnpEff.main(SnpEff.java:167)
```

Can you please provide download links for newer DB version?

**Comment by pcingola** [comment]
Released v5.0 fixing many issues with database downloads.

https://snpeff.blob.core.windows.net/versions/snpEff_latest_core.zip

**Comment by pcingola** [comment]
This should be fixed now. Please reopen if version 5.0 doesn't work.

**Comment by wtandrews** [comment]
It is still broken in version 5.

java -Xmx4g -jar snpEff.jar download -c snpEff.config -v GRCh38.86
00:00:00	SnpEff version SnpEff 5.0e (build 2021-03-09 06:01), by Pablo Cingolani
00:00:00	Command: 'download'
00:00:00	Reading configuration file 'snpEff.config'. Genome: 'GRCh38.86'
00:00:00	Reading config file: /home/..../snpEff/snpEff.config
java.lang.RuntimeException: Property: 'GRCh38.86.genome' not found
	at org.snpeff.interval.Genome.<init>(Genome.java:104)
	at org.snpeff.snpEffect.Config.readGenomeConfig(Config.java:693)
	at org.snpeff.snpEffect.Config.readConfig(Config.java:661)
	at org.snpeff.snpEffect.Config.init(Config.java:487)
	at org.snpeff.snpEffect.Config.<init>(Config.java:121)
	at org.snpeff.SnpEff.loadConfig(SnpEff.java:449)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.runDownloadGenome(SnpEffCmdDownload.java:80)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.run(SnpEffCmdDownload.java:72)
	at org.snpeff.SnpEff.run(SnpEff.java:1188)
	at org.snpeff.SnpEff.main(SnpEff.java:168)

**Comment by pcingola** [comment]
Genomic databases are not backward compatible, so it is indeed expected that version 4.5 won't work with older databases.

I've been having tons of issues with SourceForge, so in version 5.0 everything was migrated to Azure (thanks to Microsoft offering to host the project). It is recommended that you migrate to version 5.0
